### ISSUE TITLE
SUBSONIC_HOME and other vars aren't properly fixed in Subsonic install script

### ISSUE THREAD

**Issue by jsit** [userdocs/userdocs#1]
When I run the [latest Subsonic install script](https://github.com/userdocs/userdocs/blob/2203635b72123d578cc00f21361f69e5400d93da/Remote_Programs/Subsonic/install.subsonic.sh), my ~/private/subsonic/subsonic.sh script still has /var/subsonic as its SUBSONIC_HOME value, and other things are mis-set as well, causing Subsonic not to run.

The lines in Subsonic 6.1's script have changed since 6.0:

```
SUBSONIC_HOME=${SUBSONIC_HOME:-/var/subsonic}
SUBSONIC_HOST=${SUBSONIC_HOST:-0.0.0.0}
SUBSONIC_PORT=${SUBSONIC_PORT:-4040}
SUBSONIC_HTTPS_PORT=${SUBSONIC_HTTPS_PORT:-0}
SUBSONIC_CONTEXT_PATH=${SUBSONIC_CONTEXT_PATH:-/}
SUBSONIC_DB=${SUBSONIC_DB}
SUBSONIC_MAX_MEMORY=${SUBSONIC_MAX_MEMORY:-150}
SUBSONIC_PIDFILE=${SUBSONIC_PIDFILE}
SUBSONIC_DEFAULT_MUSIC_FOLDER=${SUBSONIC_DEFAULT_MUSIC_FOLDER:-/var/music}
SUBSONIC_DEFAULT_PODCAST_FOLDER=${SUBSONIC_DEFAULT_PODCAST_FOLDER:-/var/music/Podcast}
SUBSONIC_DEFAULT_PLAYLIST_FOLDER=${SUBSONIC_DEFAULT_PLAYLIST_FOLDER:-/var/playlists}
```

**Comment by userdocs** [comment]
I just updated it to work. Really the script needs a rework as it is pretty much a hammer but it should be functional as it is now.

**Comment by userdocs** [comment]
The script has been redone as of version `2.6.2`.

It now uses the userdocs template layout and installs to `~/.subsonic`  and stores generic files in `~/.userdocs`. so you might want to remove the previous installation and start over.
