### ISSUE TITLE
Jackett -c libcurl deprecated

### ISSUE THREAD

**Issue by oaeide** [userdocs/userdocs#2]
The crontab job for starting Jackett that the monoapps-script sets up is failing with the message saying that -c libcurl is deprecated, or something along those lines. Starting it without that option seems to be working fine.

**Comment by userdocs** [comment]
Thanks. I removed all references to libcurl in the startup commands and crontab generation in the script version 1.1.9

**Comment by oaeide** [comment]
Thanks. Tried it now - seems to be working 👍
