### ISSUE TITLE
script stopped working on my slot

### ISSUE THREAD

**Issue by zdiddy1** [userdocs/userdocs#3]
Irssi is not starting and now the script has started making duplicate processes ( /bin/sh). If I don't kill the cron job it'll max out the process on my slot. I believe this is happening because the slot is one that feral hardened. Some things are changed. For example if I run ps x there is no process for "autodl" like there used to be. I need to run screen -ls to see the process. The script worked flawlessly until they changed the slot. 

Update: It's the rtorrent.sh script. It's named autodlcron.sh on my slot.   it does seem the script is working  but it's creating those duplicate processes over time.

**Comment by userdocs** [comment]
which script?

**Comment by zdiddy1** [comment]
if everything is running and I kill autodl then the script runs and restarts it with no issue. If I kill rutorrent then autodl won't restart until I force kill it. Rutorrent restarts fine it seems. Then after I force kill autodl the script seems to run properly. Just creates the /bin/sh processes over time.

**Comment by userdocs** [comment]
this has to be the cronjob script. is this for the main rtorrent or for a custom installation with a suffix?

**Comment by zdiddy1** [comment]
should be a standard install. I'm on irc if you want to chat too by the way. In feral

**Comment by userdocs** [comment]
I fixed this the other day. What happened was that screen no longer shows in `ps x` and do the checks were failing and trying to restart over and over. There are also other modifications since installed it most likely. 

Use this command to update it automatically:

```
curl -sL https://git.io/vxyKo --create-dir -o ~/.userdocs/cronjobs/rtorrent.cronjob
```

**Comment by zdiddy1** [comment]
yes, that sounds like my issue. I'll test it out. Thanks. Do you want me to report back how it goes?

**Comment by userdocs** [comment]
yes please. the cronscript logs to `~/.userdocs/cronscripts/logs`

**Comment by zdiddy1** [comment]
Looks like it's running stable. No extra /bin/sh processes showing up.

**Comment by userdocs** [comment]
Keep an eye on the autodl and rtorrent cronjob love and let me know they log any odd behaviour.

**Comment by zdiddy1** [comment]
will do.

**Comment by zdiddy1** [comment]
Great Script by the way. Thanks a lot for sharing and updating it!

**Comment by zdiddy1** [comment]
Just wanted to swing by and update you. The script is stable and everything is good. No odd behavior at all. I see rtorrent was restarted from the logs, yesterday actually, and autodl is and rtorrent are running great.

**Comment by userdocs** [comment]
Thank for letting me know.
