### ISSUE TITLE
Radarr issue

### ISSUE THREAD

**Issue by oaeide** [userdocs/userdocs#4]
Hi. Trying to install radarr, and I get this error:

```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat '/media/sdd1/username/.userdocs/tmp/Radarr/.': No such file or directory
The Radarr cronjob is already in crontab

The Apache proxypass was installed

The nginx proxypass was installed

Radarr was restarted
```

(Radarr not running afterwards)

**Comment by userdocs** [comment]
The url format on the releases had changed. I have changed the script url check to match the current release url format, hopefully it will remain consistent.

Test and confirm with script version 1.1.21 please.

**Comment by oaeide** [comment]
It works perfectly. Splendid!
